language: android
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_ABI=x86_64
    # Use google_apis flavor if no default flavor emulator.
    - EMULATOR_FLAVOR=default
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_TOOLS}:${ANDROID_TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
    - ANDROID_API=21

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29

before_cache:
  - rm -rf $HOME/.m2/repository/io/michaelrocks/lightsaber-
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  # Build and publish artifacts to the local Maven repo.
  - ./gradlew assemble publishToMavenLocal -Pbootstrap=true --no-daemon --rerun-tasks
  # Mute sdkmanager warning.
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  # We need the API of the emulator we will run.
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "platforms;android-$ANDROID_API" >/dev/null
  - echo y | sdkmanager "emulator" >/dev/null
  - echo y | sdkmanager "system-images;android-$ANDROID_API;$EMULATOR_FLAVOR;$ANDROID_ABI" >/dev/null
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$ANDROID_API;$EMULATOR_FLAVOR;$ANDROID_ABI" -c 10M
  - emulator -verbose -avd test -no-accel -no-snapshot -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew check --no-daemon
  - ./gradlew connectedCheck --no-daemon
